In [63]:
#Extra function created to help me solve some problems
import re

def natural_sort(l): 
    convert = lambda text: int(text) if text.isdigit() else text.lower() 
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(l, key = alphanum_key)

def get_first_nbr_from_str(input_str):
    if not input_str and not isinstance(input_str, str):
        return 0
    out_number = ''
    for ele in input_str:
        if (ele == '.' and '.' not in out_number) or ele.isdigit():
            out_number += ele
        elif out_number:
            break
    return int(out_number)

# Giorno 2

In [1]:
import os
os.chdir('./..')
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
_BASE_PATH = 'resources/dataset/originals'

from src import data
from src.preprocessing.distances import preprocess

In [2]:
preprocess()
distances= data.distances_proprocessed()
distances

caching distances

distances loaded in: 0.082 s

shape of the dataframe is: (41054, 2)
caching distances

distances loaded in: 0.0844 s

shape of the dataframe is: (41046, 3)

                                                STATIONS   KEY    KM
0      STATION_29,10.0;STATION_37,19.0;STATION_36,40....   278   662
1      STATION_29,10.0;STATION_37,19.0;STATION_36,40....   278   663
2      STATION_29,10.0;STATION_37,19.0;STATION_36,40....   278   664
3      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   665
4      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   666
5      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   667
6      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   668
7      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   669
8      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   670
9      STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   671
10     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   672
11     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   673
12     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   674
13     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   675
14     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   676
15     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   677
16     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   678
17     STATION_29,6.0;STATION_37,17.0;STATION_36,44.0...   278   679
18     STATION_29,7.0;STATION_37,17.0;STATION_28,35.0...   278   680
19     STATION_29,7.0;STATION_37,17.0;STATION_28,35.0...   278   681
20     STATION_29,7.0;STATION_37,17.0;STATION_28,35.0...   278   682
21     STATION_29,7.0;STATION_37,17.0;STATION_28,35.0...   278   683
22     STATION_29,7.0;STATION_37,17.0;STATION_28,35.0...   278   684
23     STATION_29,7.0;STATION_37,17.0;STATION_28,35.0...   278   685
24     STATION_29,8.0;STATION_37,16.0;STATION_28,34.0...   278   686
25     STATION_29,8.0;STATION_37,16.0;STATION_28,34.0...   278   687
26     STATION_29,9.0;STATION_37,16.0;STATION_28,34.0...   278   688
27     STATION_33,54.0;STATION_29,64.0;STATION_37,73....   280   593
28     STATION_33,52.0;STATION_29,64.0;STATION_37,73....   280   594
29     STATION_33,52.0;STATION_29,64.0;STATION_37,73....   280   595
...                                                  ...   ...   ...
41016  STATION_22,17.0;STATION_27,91.0;STATION_23,124...   107  1798
41017  STATION_61,22.0;STATION_78,53.0;STATION_80,55....   530  1615
41018  STATION_61,22.0;STATION_78,53.0;STATION_80,55....   530  1614
41019  STATION_61,20.0;STATION_78,53.0;STATION_65,56....   530  1613
41020  STATION_89,8.0;STATION_54,30.0;STATION_50,69.0...    40  1929
41021  STATION_89,8.0;STATION_54,30.0;STATION_50,69.0...    40  1928
41022  STATION_89,9.0;STATION_54,31.0;STATION_50,70.0...    40  1927
41023  STATION_18,52.0;STATION_21,122.0;STATION_13,13...   406  1814
41024  STATION_18,52.0;STATION_21,122.0;STATION_13,13...   406  1813
41025  STATION_18,49.0;STATION_21,119.0;STATION_13,13...   406  1812
41026  STATION_18,49.0;STATION_21,119.0;STATION_13,13...   406  1811
41027  STATION_18,49.0;STATION_21,119.0;STATION_13,13...   406  1810
41028  STATION_18,49.0;STATION_21,119.0;STATION_13,13...   406  1809
41029  STATION_18,48.0;STATION_21,118.0;STATION_13,13...   406  1808
41030  STATION_18,48.0;STATION_21,118.0;STATION_13,13...   406  1807
41031  STATION_18,48.0;STATION_21,118.0;STATION_13,13...   406  1806
41032  STATION_18,48.0;STATION_21,118.0;STATION_13,13...   406  1805
41033  STATION_18,46.0;STATION_21,116.0;STATION_13,13...   406  1804
41034  STATION_18,46.0;STATION_21,116.0;STATION_13,13...   406  1803
41035  STATION_18,46.0;STATION_21,116.0;STATION_13,13...   406  1802
41036  STATION_0,31.0;STATION_3,51.0;STATION_69,82.0;...   555  1494
41037  STATION_0,31.0;STATION_3,51.0;STATION_69,82.0;...   555  1493
41038  STATION_0,30.0;STATION_3,50.0;STATION_69,81.0;...   555  1492
41039  STATION_0,30.0;STATION_3,50.0;STATION_69,81.0;...   555  1491
41040  STATION_0,30.0;STATION_3,49.0;STATION_69,81.0;...   555  1490
41041  STATION_0,30.0;STATION_3,49.0;STATION_69,81.0;...   555  1489
41042  STATION_15,7.0;STATION_19,15.0;STATION_21,29.0...  None  1628
41043  STATION_15,7.0;STATION_19,16.0;STATION_21,30.0...  None  1627
41044  STATION_18,68.0;STATION_21,138.0;STATION_13,15...    73  1594
41045  STATION_18,68.0;STATION_21,138.0;STATION_13,15...    73  1593

[41046 rows x 3 columns]

In [3]:
bs_hours=data.base_structure_hours()
base_structure_df =bs_hours
base_structure_df.head()

caching base structure

base structure loaded in: 3.0668 s

shape of the dataframe is: (5298840, 3)

  DATETIME_UTC  KEY   KM
0   2018-09-01    0  333
1   2018-09-01    0  337
2   2018-09-01    0  342
3   2018-09-01    0  343
4   2018-09-01    0  357

In [4]:
weather_train_df = data.weather_original()

#lavoro su uno slice di 1M
base_structure_df ["WEATHER"]=""
base_structure_df ["DISTANCE"]=np.NaN

#weather_train_df1=weather_train_df.set_index(["ID","DATETIME_UTC"])

caching resources/dataset/originals/weather_train.csv.gz

In [5]:
stations=weather_train_df[["ID"]].drop_duplicates()
stations["dummy"]=0

In [6]:
times=base_structure_df[["DATETIME_UTC"]].drop_duplicates()
times["dummy"]=0

In [7]:
bs_2=pd.merge(stations,times)
bs_2=bs_2.drop("dummy",axis=1)
bs_2

                ID        DATETIME_UTC
0        STATION_7 2018-09-01 00:00:00
1        STATION_7 2018-09-01 01:00:00
2        STATION_7 2018-09-01 02:00:00
3        STATION_7 2018-09-01 03:00:00
4        STATION_7 2018-09-01 04:00:00
5        STATION_7 2018-09-01 05:00:00
6        STATION_7 2018-09-01 06:00:00
7        STATION_7 2018-09-01 07:00:00
8        STATION_7 2018-09-01 08:00:00
9        STATION_7 2018-09-01 09:00:00
10       STATION_7 2018-09-01 10:00:00
11       STATION_7 2018-09-01 11:00:00
12       STATION_7 2018-09-01 12:00:00
13       STATION_7 2018-09-01 13:00:00
14       STATION_7 2018-09-01 14:00:00
15       STATION_7 2018-09-01 15:00:00
16       STATION_7 2018-09-01 16:00:00
17       STATION_7 2018-09-01 17:00:00
18       STATION_7 2018-09-01 18:00:00
19       STATION_7 2018-09-01 19:00:00
20       STATION_7 2018-09-01 20:00:00
21       STATION_7 2018-09-01 21:00:00
22       STATION_7 2018-09-01 22:00:00
23       STATION_7 2018-09-01 23:00:00
24       STATION_7 2018-09-02 00:00:00
25       STATION_7 2018-09-02 01:00:00
26       STATION_7 2018-09-02 02:00:00
27       STATION_7 2018-09-02 03:00:00
28       STATION_7 2018-09-02 04:00:00
29       STATION_7 2018-09-02 05:00:00
...            ...                 ...
265650  STATION_18 2018-12-31 18:00:00
265651  STATION_18 2018-12-31 19:00:00
265652  STATION_18 2018-12-31 20:00:00
265653  STATION_18 2018-12-31 21:00:00
265654  STATION_18 2018-12-31 22:00:00
265655  STATION_18 2018-12-31 23:00:00
265656  STATION_18 2019-01-01 00:00:00
265657  STATION_18 2019-01-01 01:00:00
265658  STATION_18 2019-01-01 02:00:00
265659  STATION_18 2019-01-01 03:00:00
265660  STATION_18 2019-01-01 04:00:00
265661  STATION_18 2019-01-01 05:00:00
265662  STATION_18 2019-01-01 06:00:00
265663  STATION_18 2019-01-01 07:00:00
265664  STATION_18 2019-01-01 08:00:00
265665  STATION_18 2019-01-01 09:00:00
265666  STATION_18 2019-01-01 10:00:00
265667  STATION_18 2019-01-01 11:00:00
265668  STATION_18 2019-01-01 12:00:00
265669  STATION_18 2019-01-01 13:00:00
265670  STATION_18 2019-01-01 14:00:00
265671  STATION_18 2019-01-01 15:00:00
265672  STATION_18 2019-01-01 16:00:00
265673  STATION_18 2019-01-01 17:00:00
265674  STATION_18 2019-01-01 18:00:00
265675  STATION_18 2019-01-01 19:00:00
265676  STATION_18 2019-01-01 20:00:00
265677  STATION_18 2019-01-01 21:00:00
265678  STATION_18 2019-01-01 22:00:00
265679  STATION_18 2019-01-01 23:00:00

[265680 rows x 2 columns]

In [8]:
weather_train_df2=pd.merge(bs_2,weather_train_df,how="left")
weather_train_df2

,ID,DATETIME_UTC,TEMPERATURE,MAX_TEMPERATURE,MIN_TEMPERATURE,WEATHER
0,STATION_7,2018-09-01 00:00:00,NaN,NaN,NaN,NaN
1,STATION_7,2018-09-01 01:00:00,NaN,NaN,NaN,NaN
2,STATION_7,2018-09-01 02:00:00,NaN,NaN,NaN,NaN
3,STATION_7,2018-09-01 03:00:00,NaN,NaN,NaN,NaN
4,STATION_7,2018-09-01 04:00:00,NaN,NaN,NaN,NaN
5,STATION_7,2018-09-01 05:00:00,NaN,NaN,NaN,NaN
6,STATION_7,2018-09-01 06:00:00,NaN,NaN,NaN,NaN
7,STATION_7,2018-09-01 07:00:00,NaN,NaN,NaN,NaN
8,STATION_7,2018-09-01 08:00:00,NaN,NaN,NaN,NaN
9,STATION_7,2018-09-01 09:00:00,NaN,NaN,NaN,NaN
10,STATION_7,2018-09-01 10:00:00,25.0,26.0,22.0,Quasi Sereno
11,STATION_7,2018-09-01 11:00:00,NaN,NaN,NaN,NaN
12,STATION_7,2018-09-01 12:00:00,29.0,29.0,22.0,Quasi Sereno
13,STATION_7,2018-09-01 13:00:00,NaN,NaN,NaN,NaN
14,STATION_7,2018-09-01 14:00:00,NaN,NaN,NaN,NaN
15,STATION_7,2018-09-01 15:00:00,NaN,NaN,NaN,NaN
16,STATION_7,2018-09-01 16:00:00,NaN,NaN,NaN,NaN
17,STATION_7,2018-09-01 17:00:00,NaN,NaN,NaN,NaN
18,STATION_7,2018-09-01 18:00:00,NaN,NaN,NaN,NaN
19,STATION_7,2018-09-01 19:00:00,NaN,NaN,NaN,NaN
20,STATION_7,2018-09-01 20:00:00,NaN,NaN,NaN,NaN
21,STATION_7,2018-09-01 21:00:00,NaN,NaN,NaN,NaN
22,STATION_7,2018-09-01 22:00:00,25.0,30.0,22.0,Quasi Sereno
23,STATION_7,2018-09-01 23:00:00,NaN,NaN,NaN,NaN
24,STATION_7,2018-09-02 00:00:00,23.0,30.0,22.0,Quasi Sereno
25,STATION_7,2018-09-02 01:00:00,NaN,NaN,NaN,NaN
26,STATION_7,2018-09-02 02:00:00,NaN,NaN,NaN,NaN
27,STATION_7,2018-09-02 03:00:00,NaN,NaN,NaN,NaN
28,STATION_7,2018-09-02 04:00:00,NaN,NaN,NaN,NaN
29,STATION_7,2018-09-02 05:00:00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
266666,STATION_18,2018-12-31 18:00:00,NaN,NaN,NaN,NaN
266667,STATION_18,2018-12-31 19:00:00,NaN,NaN,NaN,NaN
266668,STATION_18,2018-12-31 20:00:00,NaN,NaN,NaN,NaN
266669,STATION_18,2018-12-31 21:00:00,NaN,NaN,NaN,NaN
266670,STATION_18,2018-12-31 22:00:00,NaN,NaN,NaN,NaN
266671,STATION_18,2018-12-31 23:00:00,NaN,NaN,NaN,NaN
266672,STATION_18,2019-01-01 00:00:00,NaN,NaN,NaN,NaN
266673,STATION_18,2019-01-01 01:00:00,NaN,NaN,NaN,NaN
266674,STATION_18,2019-01-01 02:00:00,NaN,NaN,NaN,NaN
266675,STATION_18,2019-01-01 03:00:00,NaN,NaN,NaN,NaN
266676,STATION_18,2019-01-01 04:00:00,NaN,NaN,NaN,NaN
266677,STATION_18,2019-01-01 05:00:00,NaN,NaN,NaN,NaN
266678,STATION_18,2019-01-01 06:00:00,NaN,NaN,NaN,NaN
266679,STATION_18,2019-01-01 07:00:00,NaN,NaN,NaN,NaN
266680,STATION_18,2019-01-01 08:00:00,NaN,NaN,NaN,NaN
266681,STATION_18,2019-01-01 09:00:00,NaN,NaN,NaN,NaN
266682,STATION_18,2019-01-01 10:00:00,NaN,NaN,NaN,NaN
266683,STATION_18,2019-01-01 11:00:00,NaN,NaN,NaN,NaN
266684,STATION_18,2019-01-01 12:00:00,NaN,NaN,NaN,NaN
266685,STATION_18,2019-01-01 13:00:00,NaN,NaN,NaN,NaN
266686,STATION_18,2019-01-01 14:00:00,NaN,NaN,NaN,NaN
266687,STATION_18,2019-01-01 15:00:00,NaN,NaN,NaN,NaN
266688,STATION_18,2019-01-01 16:00:00,NaN,NaN,NaN,NaN
266689,STATION_18,2019-01-01 17:00:00,NaN,NaN,NaN,NaN
266690,STATION_18,2019-01-01 18:00:00,NaN,NaN,NaN,NaN
266691,STATION_18,2019-01-01 19:00:00,NaN,NaN,NaN,NaN
266692,STATION_18,2019-01-01 20:00:00,NaN,NaN,NaN,NaN
266693,STATION_18,2019-01-01 21:00:00,NaN,NaN,NaN,NaN
266694,STATION_18,2019-01-01 22:00:00,NaN,NaN,NaN,NaN
266695,STATION_18,2019-01-01 23:00:00,NaN,NaN,NaN,NaN

In [9]:
#Creazione Dizionario per le distanze
distances_dict = dict()
d=list(distances.groupby(by=["KEY","KM"]).groups.keys())
for x in tqdm(d):
    distances_dict[x] =list(map(lambda x: x.split(','), distances.loc[(distances['KEY']==x[0]) & 
                                                             (distances['KM']==x[1])].STATIONS.values[0].split(";")))

HBox(children=(IntProgress(value=0, max=41046), HTML(value='')))

In [13]:
weather_train_df2=weather_train_df2.set_index(["ID","DATETIME_UTC"])
weather_train_df2

                                TEMPERATURE  MAX_TEMPERATURE  MIN_TEMPERATURE  \
ID         DATETIME_UTC
STATION_7  2018-09-01 00:00:00          NaN              NaN              NaN
           2018-09-01 01:00:00          NaN              NaN              NaN
           2018-09-01 02:00:00          NaN              NaN              NaN
           2018-09-01 03:00:00          NaN              NaN              NaN
           2018-09-01 04:00:00          NaN              NaN              NaN
           2018-09-01 05:00:00          NaN              NaN              NaN
           2018-09-01 06:00:00          NaN              NaN              NaN
           2018-09-01 07:00:00          NaN              NaN              NaN
           2018-09-01 08:00:00          NaN              NaN              NaN
           2018-09-01 09:00:00          NaN              NaN              NaN
           2018-09-01 10:00:00         25.0             26.0             22.0
           2018-09-01 11:00:00          NaN              NaN              NaN
           2018-09-01 12:00:00         29.0             29.0             22.0
           2018-09-01 13:00:00          NaN              NaN              NaN
           2018-09-01 14:00:00          NaN              NaN              NaN
           2018-09-01 15:00:00          NaN              NaN              NaN
           2018-09-01 16:00:00          NaN              NaN              NaN
           2018-09-01 17:00:00          NaN              NaN              NaN
           2018-09-01 18:00:00          NaN              NaN              NaN
           2018-09-01 19:00:00          NaN              NaN              NaN
           2018-09-01 20:00:00          NaN              NaN              NaN
           2018-09-01 21:00:00          NaN              NaN              NaN
           2018-09-01 22:00:00         25.0             30.0             22.0
           2018-09-01 23:00:00          NaN              NaN              NaN
           2018-09-02 00:00:00         23.0             30.0             22.0
           2018-09-02 01:00:00          NaN              NaN              NaN
           2018-09-02 02:00:00          NaN              NaN              NaN
           2018-09-02 03:00:00          NaN              NaN              NaN
           2018-09-02 04:00:00          NaN              NaN              NaN
           2018-09-02 05:00:00          NaN              NaN              NaN
...                                     ...              ...              ...
STATION_18 2018-12-31 18:00:00          NaN              NaN              NaN
           2018-12-31 19:00:00          NaN              NaN              NaN
           2018-12-31 20:00:00          NaN              NaN              NaN
           2018-12-31 21:00:00          NaN              NaN              NaN
           2018-12-31 22:00:00          NaN              NaN              NaN
           2018-12-31 23:00:00          NaN              NaN              NaN
           2019-01-01 00:00:00          NaN              NaN              NaN
           2019-01-01 01:00:00          NaN              NaN              NaN
           2019-01-01 02:00:00          NaN              NaN              NaN
           2019-01-01 03:00:00          NaN              NaN              NaN
           2019-01-01 04:00:00          NaN              NaN              NaN
           2019-01-01 05:00:00          NaN              NaN              NaN
           2019-01-01 06:00:00          NaN              NaN              NaN
           2019-01-01 07:00:00          NaN              NaN              NaN
           2019-01-01 08:00:00          NaN              NaN              NaN
           2019-01-01 09:00:00          NaN              NaN              NaN
           2019-01-01 10:00:00          NaN              NaN              NaN
           2019-01-01 11:00:00          NaN              NaN              NaN
           2019-01-01 12:00:00          NaN              NaN              NaN
           2019-01-01 13:00:00          NaN              NaN              NaN
           2019-01-01 14:00:00          NaN              NaN              NaN
           2019-01-01 15:00:00          NaN              NaN              NaN
           2019-01-01 16:00:00          NaN              NaN              NaN
           2019-01-01 17:00:00          NaN              NaN              NaN
           2019-01-01 18:00:00          NaN              NaN              NaN
           2019-01-01 19:00:00          NaN              NaN              NaN
           2019-01-01 20:00:00          NaN              NaN              NaN
           2019-01-01 21:00:00          NaN              NaN              NaN
           2019-01-01 22:00:00          NaN              NaN              NaN
           2019-01-01 23:00:00          NaN              NaN              NaN

                                     WEATHER
ID         DATETIME_UTC
STATION_7  2018-09-01 00:00:00           NaN
           2018-09-01 01:00:00           NaN
           2018-09-01 02:00:00           NaN
           2018-09-01 03:00:00           NaN
           2018-09-01 04:00:00           NaN
           2018-09-01 05:00:00           NaN
           2018-09-01 06:00:00           NaN
           2018-09-01 07:00:00           NaN
           2018-09-01 08:00:00           NaN
           2018-09-01 09:00:00           NaN
           2018-09-01 10:00:00  Quasi Sereno
           2018-09-01 11:00:00           NaN
           2018-09-01 12:00:00  Quasi Sereno
           2018-09-01 13:00:00           NaN
           2018-09-01 14:00:00           NaN
           2018-09-01 15:00:00           NaN
           2018-09-01 16:00:00           NaN
           2018-09-01 17:00:00           NaN
           2018-09-01 18:00:00           NaN
           2018-09-01 19:00:00           NaN
           2018-09-01 20:00:00           NaN
           2018-09-01 21:00:00           NaN
           2018-09-01 22:00:00  Quasi Sereno
           2018-09-01 23:00:00           NaN
           2018-09-02 00:00:00  Quasi Sereno
           2018-09-02 01:00:00           NaN
           2018-09-02 02:00:00           NaN
           2018-09-02 03:00:00           NaN
           2018-09-02 04:00:00           NaN
           2018-09-02 05:00:00           NaN
...                                      ...
STATION_18 2018-12-31 18:00:00           NaN
           2018-12-31 19:00:00           NaN
           2018-12-31 20:00:00           NaN
           2018-12-31 21:00:00           NaN
           2018-12-31 22:00:00           NaN
           2018-12-31 23:00:00           NaN
           2019-01-01 00:00:00           NaN
           2019-01-01 01:00:00           NaN
           2019-01-01 02:00:00           NaN
           2019-01-01 03:00:00           NaN
           2019-01-01 04:00:00           NaN
           2019-01-01 05:00:00           NaN
           2019-01-01 06:00:00           NaN
           2019-01-01 07:00:00           NaN
           2019-01-01 08:00:00           NaN
           2019-01-01 09:00:00           NaN
           2019-01-01 10:00:00           NaN
           2019-01-01 11:00:00           NaN
           2019-01-01 12:00:00           NaN
           2019-01-01 13:00:00           NaN
           2019-01-01 14:00:00           NaN
           2019-01-01 15:00:00           NaN
           2019-01-01 16:00:00           NaN
           2019-01-01 17:00:00           NaN
           2019-01-01 18:00:00           NaN
           2019-01-01 19:00:00           NaN
           2019-01-01 20:00:00           NaN
           2019-01-01 21:00:00           NaN
           2019-01-01 22:00:00           NaN
           2019-01-01 23:00:00           NaN

[266696 rows x 4 columns]

In [22]:
import math

base_structure_df ["WEATHER"]=""
base_structure_df ["DISTANCE"]=np.NaN



for i,row in tqdm(base_structure_df.iterrows()):
    date=row.DATETIME_UTC
    
    stations=distances_dict[(str(row.KEY),row.KM)]
    weather = np.NaN
    it=0
    
    while not isinstance(weather, str):
        #get station and dist from dict
        station=stations[it][0]
        distance=stations[it][1]

        weather=weather_train_df2.loc[(station,date)].WEATHER.values[0]
        it+=1
        if it>= len(stations):
            print("NON PRESENTE")
            print (row)
            break
    
    base_structure_df.at[i,'WEATHER'] = weather
    base_structure_df.at[i,'DISTANCE'] = distance

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: PerformanceWarning: indexing past lexsort depth may impact performance.

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              333
WEATHER
DISTANCE                        NaN
Name: 1795, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              337
WEATHER
DISTANCE                        NaN
Name: 1796, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              342
WEATHER
DISTANCE                        NaN
Name: 1797, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              343
WEATHER
DISTANCE                        NaN
Name: 1798, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              357
WEATHER
DISTANCE                        NaN
Name: 1799, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              385
WEATHER
DISTANCE                        NaN
Name: 1800, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              407
WEATHER
DISTANCE                        NaN
Name: 1801, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              411
WEATHER
DISTANCE                        NaN
Name: 1802, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              423
WEATHER
DISTANCE                        NaN
Name: 1803, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              443
WEATHER
DISTANCE                        NaN
Name: 1804, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              454
WEATHER
DISTANCE                        NaN
Name: 1805, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              488
WEATHER
DISTANCE                        NaN
Name: 1806, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               0
KM                              520
WEATHER
DISTANCE                        NaN
Name: 1807, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1480
WEATHER
DISTANCE                        NaN
Name: 1808, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1512
WEATHER
DISTANCE                        NaN
Name: 1809, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1546
WEATHER
DISTANCE                        NaN
Name: 1810, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1557
WEATHER
DISTANCE                        NaN
Name: 1811, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1577
WEATHER
DISTANCE                        NaN
Name: 1812, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1589
WEATHER
DISTANCE                        NaN
Name: 1813, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1593
WEATHER
DISTANCE                        NaN
Name: 1814, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1615
WEATHER
DISTANCE                        NaN
Name: 1815, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1643
WEATHER
DISTANCE                        NaN
Name: 1816, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1657
WEATHER
DISTANCE                        NaN
Name: 1817, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1658
WEATHER
DISTANCE                        NaN
Name: 1818, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1663
WEATHER
DISTANCE                        NaN
Name: 1819, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               1
KM                             1667
WEATHER
DISTANCE                        NaN
Name: 1820, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              10
KM                               79
WEATHER
DISTANCE                        NaN
Name: 1821, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             100
KM                              577
WEATHER
DISTANCE                        NaN
Name: 1822, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             101
KM                             1423
WEATHER
DISTANCE                        NaN
Name: 1823, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             102
KM                              837
WEATHER
DISTANCE                        NaN
Name: 1824, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             102
KM                              877
WEATHER
DISTANCE                        NaN
Name: 1825, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             102
KM                              918
WEATHER
DISTANCE                        NaN
Name: 1826, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             102
KM                              933
WEATHER
DISTANCE                        NaN
Name: 1827, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             102
KM                              949
WEATHER
DISTANCE                        NaN
Name: 1828, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             103
KM                             1051
WEATHER
DISTANCE                        NaN
Name: 1829, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             103
KM                             1067
WEATHER
DISTANCE                        NaN
Name: 1830, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             103
KM                             1082
WEATHER
DISTANCE                        NaN
Name: 1831, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             103
KM                             1123
WEATHER
DISTANCE                        NaN
Name: 1832, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             103
KM                             1163
WEATHER
DISTANCE                        NaN
Name: 1833, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             104
KM                              719
WEATHER
DISTANCE                        NaN
Name: 1834, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             104
KM                              749
WEATHER
DISTANCE                        NaN
Name: 1835, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             105
KM                             1251
WEATHER
DISTANCE                        NaN
Name: 1836, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             105
KM                             1281
WEATHER
DISTANCE                        NaN
Name: 1837, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             106
KM                              190
WEATHER
DISTANCE                        NaN
Name: 1838, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             107
KM                             1810
WEATHER
DISTANCE                        NaN
Name: 1839, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             108
KM                              108
WEATHER
DISTANCE                        NaN
Name: 1840, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             108
KM                              148
WEATHER
DISTANCE                        NaN
Name: 1841, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             108
KM                              175
WEATHER
DISTANCE                        NaN
Name: 1842, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             108
KM                              210
WEATHER
DISTANCE                        NaN
Name: 1843, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             108
KM                              253
WEATHER
DISTANCE                        NaN
Name: 1844, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             109
KM                             1747
WEATHER
DISTANCE                        NaN
Name: 1845, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             109
KM                             1790
WEATHER
DISTANCE                        NaN
Name: 1846, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             109
KM                             1825
WEATHER
DISTANCE                        NaN
Name: 1847, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             109
KM                             1852
WEATHER
DISTANCE                        NaN
Name: 1848, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             109
KM                             1892
WEATHER
DISTANCE                        NaN
Name: 1849, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              11
KM                             1921
WEATHER
DISTANCE                        NaN
Name: 1850, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             110
KM                              613
WEATHER
DISTANCE                        NaN
Name: 1851, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             110
KM                              661
WEATHER
DISTANCE                        NaN
Name: 1852, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             111
KM                             1339
WEATHER
DISTANCE                        NaN
Name: 1853, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             111
KM                             1387
WEATHER
DISTANCE                        NaN
Name: 1854, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             112
KM                              590
WEATHER
DISTANCE                        NaN
Name: 1855, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             112
KM                              610
WEATHER
DISTANCE                        NaN
Name: 1856, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             112
KM                              644
WEATHER
DISTANCE                        NaN
Name: 1857, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             113
KM                             1356
WEATHER
DISTANCE                        NaN
Name: 1858, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             113
KM                             1390
WEATHER
DISTANCE                        NaN
Name: 1859, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             113
KM                             1410
WEATHER
DISTANCE                        NaN
Name: 1860, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              175
WEATHER
DISTANCE                        NaN
Name: 1861, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              215
WEATHER
DISTANCE                        NaN
Name: 1862, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              229
WEATHER
DISTANCE                        NaN
Name: 1863, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              272
WEATHER
DISTANCE                        NaN
Name: 1864, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              297
WEATHER
DISTANCE                        NaN
Name: 1865, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              308
WEATHER
DISTANCE                        NaN
Name: 1866, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              327
WEATHER
DISTANCE                        NaN
Name: 1867, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              346
WEATHER
DISTANCE                        NaN
Name: 1868, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              358
WEATHER
DISTANCE                        NaN
Name: 1869, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             114
KM                              377
WEATHER
DISTANCE                        NaN
Name: 1870, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1623
WEATHER
DISTANCE                        NaN
Name: 1871, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1642
WEATHER
DISTANCE                        NaN
Name: 1872, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1654
WEATHER
DISTANCE                        NaN
Name: 1873, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1673
WEATHER
DISTANCE                        NaN
Name: 1874, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1692
WEATHER
DISTANCE                        NaN
Name: 1875, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1703
WEATHER
DISTANCE                        NaN
Name: 1876, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1728
WEATHER
DISTANCE                        NaN
Name: 1877, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1771
WEATHER
DISTANCE                        NaN
Name: 1878, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1785
WEATHER
DISTANCE                        NaN
Name: 1879, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             115
KM                             1825
WEATHER
DISTANCE                        NaN
Name: 1880, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             116
KM                              224
WEATHER
DISTANCE                        NaN
Name: 1881, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             116
KM                              241
WEATHER
DISTANCE                        NaN
Name: 1882, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             117
KM                             1759
WEATHER
DISTANCE                        NaN
Name: 1883, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             117
KM                             1776
WEATHER
DISTANCE                        NaN
Name: 1884, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              398
WEATHER
DISTANCE                        NaN
Name: 1885, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              422
WEATHER
DISTANCE                        NaN
Name: 1886, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              428
WEATHER
DISTANCE                        NaN
Name: 1887, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              488
WEATHER
DISTANCE                        NaN
Name: 1888, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              537
WEATHER
DISTANCE                        NaN
Name: 1889, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              578
WEATHER
DISTANCE                        NaN
Name: 1890, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             118
KM                              604
WEATHER
DISTANCE                        NaN
Name: 1891, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1396
WEATHER
DISTANCE                        NaN
Name: 1892, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1422
WEATHER
DISTANCE                        NaN
Name: 1893, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1463
WEATHER
DISTANCE                        NaN
Name: 1894, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1512
WEATHER
DISTANCE                        NaN
Name: 1895, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1572
WEATHER
DISTANCE                        NaN
Name: 1896, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1578
WEATHER
DISTANCE                        NaN
Name: 1897, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             119
KM                             1602
WEATHER
DISTANCE                        NaN
Name: 1898, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              12
KM                               50
WEATHER
DISTANCE                        NaN
Name: 1899, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             120
KM                              127
WEATHER
DISTANCE                        NaN
Name: 1900, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             121
KM                             1873
WEATHER
DISTANCE                        NaN
Name: 1901, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              567
WEATHER
DISTANCE                        NaN
Name: 1902, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              590
WEATHER
DISTANCE                        NaN
Name: 1903, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              604
WEATHER
DISTANCE                        NaN
Name: 1904, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              610
WEATHER
DISTANCE                        NaN
Name: 1905, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              660
WEATHER
DISTANCE                        NaN
Name: 1906, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              668
WEATHER
DISTANCE                        NaN
Name: 1907, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              669
WEATHER
DISTANCE                        NaN
Name: 1908, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              679
WEATHER
DISTANCE                        NaN
Name: 1909, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              680
WEATHER
DISTANCE                        NaN
Name: 1910, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             122
KM                              701
WEATHER
DISTANCE                        NaN
Name: 1911, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1299
WEATHER
DISTANCE                        NaN
Name: 1912, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1320
WEATHER
DISTANCE                        NaN
Name: 1913, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1321
WEATHER
DISTANCE                        NaN
Name: 1914, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1331
WEATHER
DISTANCE                        NaN
Name: 1915, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1332
WEATHER
DISTANCE                        NaN
Name: 1916, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1340
WEATHER
DISTANCE                        NaN
Name: 1917, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1390
WEATHER
DISTANCE                        NaN
Name: 1918, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1396
WEATHER
DISTANCE                        NaN
Name: 1919, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1410
WEATHER
DISTANCE                        NaN
Name: 1920, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             123
KM                             1433
WEATHER
DISTANCE                        NaN
Name: 1921, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             124
KM                              735
WEATHER
DISTANCE                        NaN
Name: 1922, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             125
KM                             1265
WEATHER
DISTANCE                        NaN
Name: 1923, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             126
KM                               74
WEATHER
DISTANCE                        NaN
Name: 1924, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             127
KM                             1926
WEATHER
DISTANCE                        NaN
Name: 1925, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             128
KM                              599
WEATHER
DISTANCE                        NaN
Name: 1926, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             129
KM                             1401
WEATHER
DISTANCE                        NaN
Name: 1927, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              13
KM                             1950
WEATHER
DISTANCE                        NaN
Name: 1928, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             130
KM                              667
WEATHER
DISTANCE                        NaN
Name: 1929, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             130
KM                              870
WEATHER
DISTANCE                        NaN
Name: 1930, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             131
KM                             1130
WEATHER
DISTANCE                        NaN
Name: 1931, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             131
KM                             1333
WEATHER
DISTANCE                        NaN
Name: 1932, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             132
KM                              655
WEATHER
DISTANCE                        NaN
Name: 1933, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             132
KM                              675
WEATHER
DISTANCE                        NaN
Name: 1934, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             133
KM                             1325
WEATHER
DISTANCE                        NaN
Name: 1935, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             133
KM                             1345
WEATHER
DISTANCE                        NaN
Name: 1936, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             134
KM                              108
WEATHER
DISTANCE                        NaN
Name: 1937, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             134
KM                              130
WEATHER
DISTANCE                        NaN
Name: 1938, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             134
KM                              226
WEATHER
DISTANCE                        NaN
Name: 1939, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             134
KM                               75
WEATHER
DISTANCE                        NaN
Name: 1940, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             134
KM                               85
WEATHER
DISTANCE                        NaN
Name: 1941, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             135
KM                             1774
WEATHER
DISTANCE                        NaN
Name: 1942, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             135
KM                             1870
WEATHER
DISTANCE                        NaN
Name: 1943, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             135
KM                             1892
WEATHER
DISTANCE                        NaN
Name: 1944, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             135
KM                             1915
WEATHER
DISTANCE                        NaN
Name: 1945, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             135
KM                             1925
WEATHER
DISTANCE                        NaN
Name: 1946, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             136
KM                              226
WEATHER
DISTANCE                        NaN
Name: 1947, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             137
KM                             1774
WEATHER
DISTANCE                        NaN
Name: 1948, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             138
KM                              513
WEATHER
DISTANCE                        NaN
Name: 1949, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             138
KM                              533
WEATHER
DISTANCE                        NaN
Name: 1950, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             139
KM                             1467
WEATHER
DISTANCE                        NaN
Name: 1951, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             139
KM                             1487
WEATHER
DISTANCE                        NaN
Name: 1952, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1045
WEATHER
DISTANCE                        NaN
Name: 1953, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1070
WEATHER
DISTANCE                        NaN
Name: 1954, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1073
WEATHER
DISTANCE                        NaN
Name: 1955, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1100
WEATHER
DISTANCE                        NaN
Name: 1956, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1102
WEATHER
DISTANCE                        NaN
Name: 1957, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1127
WEATHER
DISTANCE                        NaN
Name: 1958, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1145
WEATHER
DISTANCE                        NaN
Name: 1959, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1177
WEATHER
DISTANCE                        NaN
Name: 1960, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1239
WEATHER
DISTANCE                        NaN
Name: 1961, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                             1282
WEATHER
DISTANCE                        NaN
Name: 1962, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                              845
WEATHER
DISTANCE                        NaN
Name: 1963, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                              901
WEATHER
DISTANCE                        NaN
Name: 1964, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                              923
WEATHER
DISTANCE                        NaN
Name: 1965, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                              956
WEATHER
DISTANCE                        NaN
Name: 1966, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              14
KM                              973
WEATHER
DISTANCE                        NaN
Name: 1967, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             140
KM                              584
WEATHER
DISTANCE                        NaN
Name: 1968, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             140
KM                              592
WEATHER
DISTANCE                        NaN
Name: 1969, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             141
KM                             1408
WEATHER
DISTANCE                        NaN
Name: 1970, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             141
KM                             1416
WEATHER
DISTANCE                        NaN
Name: 1971, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             142
KM                              462
WEATHER
DISTANCE                        NaN
Name: 1972, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             142
KM                              503
WEATHER
DISTANCE                        NaN
Name: 1973, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             143
KM                             1497
WEATHER
DISTANCE                        NaN
Name: 1974, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             143
KM                             1538
WEATHER
DISTANCE                        NaN
Name: 1975, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             143
KM                             1558
WEATHER
DISTANCE                        NaN
Name: 1976, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             144
KM                              813
WEATHER
DISTANCE                        NaN
Name: 1977, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             145
KM                             1187
WEATHER
DISTANCE                        NaN
Name: 1978, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1050
WEATHER
DISTANCE                        NaN
Name: 1979, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1074
WEATHER
DISTANCE                        NaN
Name: 1980, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1095
WEATHER
DISTANCE                        NaN
Name: 1981, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1118
WEATHER
DISTANCE                        NaN
Name: 1982, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1174
WEATHER
DISTANCE                        NaN
Name: 1983, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1186
WEATHER
DISTANCE                        NaN
Name: 1984, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1194
WEATHER
DISTANCE                        NaN
Name: 1985, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1250
WEATHER
DISTANCE                        NaN
Name: 1986, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1366
WEATHER
DISTANCE                        NaN
Name: 1987, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1401
WEATHER
DISTANCE                        NaN
Name: 1988, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1445
WEATHER
DISTANCE                        NaN
Name: 1989, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1473
WEATHER
DISTANCE                        NaN
Name: 1990, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1488
WEATHER
DISTANCE                        NaN
Name: 1991, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1494
WEATHER
DISTANCE                        NaN
Name: 1992, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1497
WEATHER
DISTANCE                        NaN
Name: 1993, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1504
WEATHER
DISTANCE                        NaN
Name: 1994, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1549
WEATHER
DISTANCE                        NaN
Name: 1995, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1612
WEATHER
DISTANCE                        NaN
Name: 1996, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1613
WEATHER
DISTANCE                        NaN
Name: 1997, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1656
WEATHER
DISTANCE                        NaN
Name: 1998, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1657
WEATHER
DISTANCE                        NaN
Name: 1999, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1660
WEATHER
DISTANCE                        NaN
Name: 2000, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                             1679
WEATHER
DISTANCE                        NaN
Name: 2001, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              811
WEATHER
DISTANCE                        NaN
Name: 2002, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              876
WEATHER
DISTANCE                        NaN
Name: 2003, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              904
WEATHER
DISTANCE                        NaN
Name: 2004, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              919
WEATHER
DISTANCE                        NaN
Name: 2005, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              925
WEATHER
DISTANCE                        NaN
Name: 2006, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              939
WEATHER
DISTANCE                        NaN
Name: 2007, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              990
WEATHER
DISTANCE                        NaN
Name: 2008, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             146
KM                              997
WEATHER
DISTANCE                        NaN
Name: 2009, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1003
WEATHER
DISTANCE                        NaN
Name: 2010, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1010
WEATHER
DISTANCE                        NaN
Name: 2011, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1061
WEATHER
DISTANCE                        NaN
Name: 2012, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1075
WEATHER
DISTANCE                        NaN
Name: 2013, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1081
WEATHER
DISTANCE                        NaN
Name: 2014, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1096
WEATHER
DISTANCE                        NaN
Name: 2015, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1124
WEATHER
DISTANCE                        NaN
Name: 2016, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                             1189
WEATHER
DISTANCE                        NaN
Name: 2017, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              321
WEATHER
DISTANCE                        NaN
Name: 2018, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              340
WEATHER
DISTANCE                        NaN
Name: 2019, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              343
WEATHER
DISTANCE                        NaN
Name: 2020, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              344
WEATHER
DISTANCE                        NaN
Name: 2021, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              387
WEATHER
DISTANCE                        NaN
Name: 2022, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              388
WEATHER
DISTANCE                        NaN
Name: 2023, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              451
WEATHER
DISTANCE                        NaN
Name: 2024, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              496
WEATHER
DISTANCE                        NaN
Name: 2025, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              503
WEATHER
DISTANCE                        NaN
Name: 2026, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              506
WEATHER
DISTANCE                        NaN
Name: 2027, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              512
WEATHER
DISTANCE                        NaN
Name: 2028, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              527
WEATHER
DISTANCE                        NaN
Name: 2029, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              555
WEATHER
DISTANCE                        NaN
Name: 2030, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              599
WEATHER
DISTANCE                        NaN
Name: 2031, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              634
WEATHER
DISTANCE                        NaN
Name: 2032, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              674
WEATHER
DISTANCE                        NaN
Name: 2033, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              750
WEATHER
DISTANCE                        NaN
Name: 2034, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              806
WEATHER
DISTANCE                        NaN
Name: 2035, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              814
WEATHER
DISTANCE                        NaN
Name: 2036, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              826
WEATHER
DISTANCE                        NaN
Name: 2037, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              905
WEATHER
DISTANCE                        NaN
Name: 2038, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              926
WEATHER
DISTANCE                        NaN
Name: 2039, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             147
KM                              950
WEATHER
DISTANCE                        NaN
Name: 2040, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             148
KM                              487
WEATHER
DISTANCE                        NaN
Name: 2041, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             148
KM                              499
WEATHER
DISTANCE                        NaN
Name: 2042, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             149
KM                             1501
WEATHER
DISTANCE                        NaN
Name: 2043, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             149
KM                             1513
WEATHER
DISTANCE                        NaN
Name: 2044, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                             1027
WEATHER
DISTANCE                        NaN
Name: 2045, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                             1044
WEATHER
DISTANCE                        NaN
Name: 2046, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                             1077
WEATHER
DISTANCE                        NaN
Name: 2047, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                             1099
WEATHER
DISTANCE                        NaN
Name: 2048, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                             1155
WEATHER
DISTANCE                        NaN
Name: 2049, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              718
WEATHER
DISTANCE                        NaN
Name: 2050, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              761
WEATHER
DISTANCE                        NaN
Name: 2051, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              823
WEATHER
DISTANCE                        NaN
Name: 2052, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              855
WEATHER
DISTANCE                        NaN
Name: 2053, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              873
WEATHER
DISTANCE                        NaN
Name: 2054, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              898
WEATHER
DISTANCE                        NaN
Name: 2055, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              900
WEATHER
DISTANCE                        NaN
Name: 2056, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              927
WEATHER
DISTANCE                        NaN
Name: 2057, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              930
WEATHER
DISTANCE                        NaN
Name: 2058, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              15
KM                              955
WEATHER
DISTANCE                        NaN
Name: 2059, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             150
KM                              626
WEATHER
DISTANCE                        NaN
Name: 2060, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             150
KM                              638
WEATHER
DISTANCE                        NaN
Name: 2061, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             150
KM                              645
WEATHER
DISTANCE                        NaN
Name: 2062, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             150
KM                              669
WEATHER
DISTANCE                        NaN
Name: 2063, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             150
KM                              670
WEATHER
DISTANCE                        NaN
Name: 2064, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             151
KM                             1330
WEATHER
DISTANCE                        NaN
Name: 2065, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             151
KM                             1331
WEATHER
DISTANCE                        NaN
Name: 2066, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             151
KM                             1355
WEATHER
DISTANCE                        NaN
Name: 2067, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             151
KM                             1362
WEATHER
DISTANCE                        NaN
Name: 2068, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             151
KM                             1374
WEATHER
DISTANCE                        NaN
Name: 2069, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             152
KM                              955
WEATHER
DISTANCE                        NaN
Name: 2070, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             153
KM                             1045
WEATHER
DISTANCE                        NaN
Name: 2071, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             154
KM                              471
WEATHER
DISTANCE                        NaN
Name: 2072, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             154
KM                              504
WEATHER
DISTANCE                        NaN
Name: 2073, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             155
KM                             1496
WEATHER
DISTANCE                        NaN
Name: 2074, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             155
KM                             1529
WEATHER
DISTANCE                        NaN
Name: 2075, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             156
KM                              384
WEATHER
DISTANCE                        NaN
Name: 2076, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             157
KM                             1616
WEATHER
DISTANCE                        NaN
Name: 2077, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              324
WEATHER
DISTANCE                        NaN
Name: 2078, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              337
WEATHER
DISTANCE                        NaN
Name: 2079, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              374
WEATHER
DISTANCE                        NaN
Name: 2080, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              382
WEATHER
DISTANCE                        NaN
Name: 2081, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              412
WEATHER
DISTANCE                        NaN
Name: 2082, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              425
WEATHER
DISTANCE                        NaN
Name: 2083, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              481
WEATHER
DISTANCE                        NaN
Name: 2084, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              519
WEATHER
DISTANCE                        NaN
Name: 2085, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              600
WEATHER
DISTANCE                        NaN
Name: 2086, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              639
WEATHER
DISTANCE                        NaN
Name: 2087, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             158
KM                              653
WEATHER
DISTANCE                        NaN
Name: 2088, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1347
WEATHER
DISTANCE                        NaN
Name: 2089, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1361
WEATHER
DISTANCE                        NaN
Name: 2090, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1400
WEATHER
DISTANCE                        NaN
Name: 2091, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1481
WEATHER
DISTANCE                        NaN
Name: 2092, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1519
WEATHER
DISTANCE                        NaN
Name: 2093, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1575
WEATHER
DISTANCE                        NaN
Name: 2094, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1588
WEATHER
DISTANCE                        NaN
Name: 2095, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1618
WEATHER
DISTANCE                        NaN
Name: 2096, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1626
WEATHER
DISTANCE                        NaN
Name: 2097, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1663
WEATHER
DISTANCE                        NaN
Name: 2098, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             159
KM                             1676
WEATHER
DISTANCE                        NaN
Name: 2099, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              549
WEATHER
DISTANCE                        NaN
Name: 2100, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              555
WEATHER
DISTANCE                        NaN
Name: 2101, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              556
WEATHER
DISTANCE                        NaN
Name: 2102, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              562
WEATHER
DISTANCE                        NaN
Name: 2103, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              569
WEATHER
DISTANCE                        NaN
Name: 2104, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              573
WEATHER
DISTANCE                        NaN
Name: 2105, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              576
WEATHER
DISTANCE                        NaN
Name: 2106, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              581
WEATHER
DISTANCE                        NaN
Name: 2107, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              585
WEATHER
DISTANCE                        NaN
Name: 2108, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              588
WEATHER
DISTANCE                        NaN
Name: 2109, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              590
WEATHER
DISTANCE                        NaN
Name: 2110, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              591
WEATHER
DISTANCE                        NaN
Name: 2111, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              597
WEATHER
DISTANCE                        NaN
Name: 2112, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              601
WEATHER
DISTANCE                        NaN
Name: 2113, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              605
WEATHER
DISTANCE                        NaN
Name: 2114, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              607
WEATHER
DISTANCE                        NaN
Name: 2115, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              612
WEATHER
DISTANCE                        NaN
Name: 2116, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              16
KM                              615
WEATHER
DISTANCE                        NaN
Name: 2117, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             160
KM                              263
WEATHER
DISTANCE                        NaN
Name: 2118, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             161
KM                             1737
WEATHER
DISTANCE                        NaN
Name: 2119, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             162
KM                              314
WEATHER
DISTANCE                        NaN
Name: 2120, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             163
KM                             1686
WEATHER
DISTANCE                        NaN
Name: 2121, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              187
WEATHER
DISTANCE                        NaN
Name: 2122, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              196
WEATHER
DISTANCE                        NaN
Name: 2123, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              204
WEATHER
DISTANCE                        NaN
Name: 2124, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              207
WEATHER
DISTANCE                        NaN
Name: 2125, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              246
WEATHER
DISTANCE                        NaN
Name: 2126, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              256
WEATHER
DISTANCE                        NaN
Name: 2127, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             164
KM                              264
WEATHER
DISTANCE                        NaN
Name: 2128, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1736
WEATHER
DISTANCE                        NaN
Name: 2129, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1744
WEATHER
DISTANCE                        NaN
Name: 2130, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1754
WEATHER
DISTANCE                        NaN
Name: 2131, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1793
WEATHER
DISTANCE                        NaN
Name: 2132, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1796
WEATHER
DISTANCE                        NaN
Name: 2133, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1804
WEATHER
DISTANCE                        NaN
Name: 2134, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             165
KM                             1813
WEATHER
DISTANCE                        NaN
Name: 2135, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             166
KM                              716
WEATHER
DISTANCE                        NaN
Name: 2136, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             166
KM                              768
WEATHER
DISTANCE                        NaN
Name: 2137, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             166
KM                              778
WEATHER
DISTANCE                        NaN
Name: 2138, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             167
KM                             1222
WEATHER
DISTANCE                        NaN
Name: 2139, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             167
KM                             1232
WEATHER
DISTANCE                        NaN
Name: 2140, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             167
KM                             1284
WEATHER
DISTANCE                        NaN
Name: 2141, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             168
KM                              809
WEATHER
DISTANCE                        NaN
Name: 2142, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             169
KM                             1191
WEATHER
DISTANCE                        NaN
Name: 2143, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1385
WEATHER
DISTANCE                        NaN
Name: 2144, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1388
WEATHER
DISTANCE                        NaN
Name: 2145, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1393
WEATHER
DISTANCE                        NaN
Name: 2146, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1395
WEATHER
DISTANCE                        NaN
Name: 2147, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1399
WEATHER
DISTANCE                        NaN
Name: 2148, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1403
WEATHER
DISTANCE                        NaN
Name: 2149, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1409
WEATHER
DISTANCE                        NaN
Name: 2150, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1410
WEATHER
DISTANCE                        NaN
Name: 2151, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1412
WEATHER
DISTANCE                        NaN
Name: 2152, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1415
WEATHER
DISTANCE                        NaN
Name: 2153, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1419
WEATHER
DISTANCE                        NaN
Name: 2154, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1424
WEATHER
DISTANCE                        NaN
Name: 2155, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1427
WEATHER
DISTANCE                        NaN
Name: 2156, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1431
WEATHER
DISTANCE                        NaN
Name: 2157, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1438
WEATHER
DISTANCE                        NaN
Name: 2158, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1444
WEATHER
DISTANCE                        NaN
Name: 2159, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1445
WEATHER
DISTANCE                        NaN
Name: 2160, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              17
KM                             1451
WEATHER
DISTANCE                        NaN
Name: 2161, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             170
KM                              255
WEATHER
DISTANCE                        NaN
Name: 2162, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             170
KM                              279
WEATHER
DISTANCE                        NaN
Name: 2163, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             170
KM                              303
WEATHER
DISTANCE                        NaN
Name: 2164, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             171
KM                             1697
WEATHER
DISTANCE                        NaN
Name: 2165, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             171
KM                             1721
WEATHER
DISTANCE                        NaN
Name: 2166, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             171
KM                             1745
WEATHER
DISTANCE                        NaN
Name: 2167, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              102
WEATHER
DISTANCE                        NaN
Name: 2168, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              110
WEATHER
DISTANCE                        NaN
Name: 2169, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              122
WEATHER
DISTANCE                        NaN
Name: 2170, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              137
WEATHER
DISTANCE                        NaN
Name: 2171, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              150
WEATHER
DISTANCE                        NaN
Name: 2172, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              166
WEATHER
DISTANCE                        NaN
Name: 2173, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              178
WEATHER
DISTANCE                        NaN
Name: 2174, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              217
WEATHER
DISTANCE                        NaN
Name: 2175, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             172
KM                              227
WEATHER
DISTANCE                        NaN
Name: 2176, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1773
WEATHER
DISTANCE                        NaN
Name: 2177, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1783
WEATHER
DISTANCE                        NaN
Name: 2178, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1822
WEATHER
DISTANCE                        NaN
Name: 2179, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1834
WEATHER
DISTANCE                        NaN
Name: 2180, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1850
WEATHER
DISTANCE                        NaN
Name: 2181, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1863
WEATHER
DISTANCE                        NaN
Name: 2182, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1878
WEATHER
DISTANCE                        NaN
Name: 2183, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1890
WEATHER
DISTANCE                        NaN
Name: 2184, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             173
KM                             1898
WEATHER
DISTANCE                        NaN
Name: 2185, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             174
KM                              598
WEATHER
DISTANCE                        NaN
Name: 2186, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             175
KM                             1402
WEATHER
DISTANCE                        NaN
Name: 2187, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             176
KM                              310
WEATHER
DISTANCE                        NaN
Name: 2188, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             176
KM                              363
WEATHER
DISTANCE                        NaN
Name: 2189, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             176
KM                              367
WEATHER
DISTANCE                        NaN
Name: 2190, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             177
KM                             1633
WEATHER
DISTANCE                        NaN
Name: 2191, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             177
KM                             1637
WEATHER
DISTANCE                        NaN
Name: 2192, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             177
KM                             1690
WEATHER
DISTANCE                        NaN
Name: 2193, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1015
WEATHER
DISTANCE                        NaN
Name: 2194, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1042
WEATHER
DISTANCE                        NaN
Name: 2195, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1097
WEATHER
DISTANCE                        NaN
Name: 2196, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1110
WEATHER
DISTANCE                        NaN
Name: 2197, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1133
WEATHER
DISTANCE                        NaN
Name: 2198, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1141
WEATHER
DISTANCE                        NaN
Name: 2199, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1168
WEATHER
DISTANCE                        NaN
Name: 2200, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1189
WEATHER
DISTANCE                        NaN
Name: 2201, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1240
WEATHER
DISTANCE                        NaN
Name: 2202, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1254
WEATHER
DISTANCE                        NaN
Name: 2203, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1283
WEATHER
DISTANCE                        NaN
Name: 2204, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1286
WEATHER
DISTANCE                        NaN
Name: 2205, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1295
WEATHER
DISTANCE                        NaN
Name: 2206, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1306
WEATHER
DISTANCE                        NaN
Name: 2207, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                             1324
WEATHER
DISTANCE                        NaN
Name: 2208, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                              874
WEATHER
DISTANCE                        NaN
Name: 2209, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                              894
WEATHER
DISTANCE                        NaN
Name: 2210, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                              903
WEATHER
DISTANCE                        NaN
Name: 2211, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                              907
WEATHER
DISTANCE                        NaN
Name: 2212, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             178
KM                              961
WEATHER
DISTANCE                        NaN
Name: 2213, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                             1093
WEATHER
DISTANCE                        NaN
Name: 2214, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                             1097
WEATHER
DISTANCE                        NaN
Name: 2215, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                             1106
WEATHER
DISTANCE                        NaN
Name: 2216, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                             1126
WEATHER
DISTANCE                        NaN
Name: 2217, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              676
WEATHER
DISTANCE                        NaN
Name: 2218, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              694
WEATHER
DISTANCE                        NaN
Name: 2219, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              705
WEATHER
DISTANCE                        NaN
Name: 2220, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              714
WEATHER
DISTANCE                        NaN
Name: 2221, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              717
WEATHER
DISTANCE                        NaN
Name: 2222, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              746
WEATHER
DISTANCE                        NaN
Name: 2223, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              760
WEATHER
DISTANCE                        NaN
Name: 2224, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              811
WEATHER
DISTANCE                        NaN
Name: 2225, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              832
WEATHER
DISTANCE                        NaN
Name: 2226, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              859
WEATHER
DISTANCE                        NaN
Name: 2227, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              867
WEATHER
DISTANCE                        NaN
Name: 2228, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              890
WEATHER
DISTANCE                        NaN
Name: 2229, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              903
WEATHER
DISTANCE                        NaN
Name: 2230, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              958
WEATHER
DISTANCE                        NaN
Name: 2231, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             179
KM                              985
WEATHER
DISTANCE                        NaN
Name: 2232, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              18
KM                              101
WEATHER
DISTANCE                        NaN
Name: 2233, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              18
KM                              105
WEATHER
DISTANCE                        NaN
Name: 2234, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              18
KM                              109
WEATHER
DISTANCE                        NaN
Name: 2235, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              18
KM                              110
WEATHER
DISTANCE                        NaN
Name: 2236, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             180
KM                              513
WEATHER
DISTANCE                        NaN
Name: 2237, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             180
KM                              524
WEATHER
DISTANCE                        NaN
Name: 2238, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             180
KM                              541
WEATHER
DISTANCE                        NaN
Name: 2239, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             180
KM                              546
WEATHER
DISTANCE                        NaN
Name: 2240, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             180
KM                              571
WEATHER
DISTANCE                        NaN
Name: 2241, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             181
KM                             1429
WEATHER
DISTANCE                        NaN
Name: 2242, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             181
KM                             1454
WEATHER
DISTANCE                        NaN
Name: 2243, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             181
KM                             1459
WEATHER
DISTANCE                        NaN
Name: 2244, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             181
KM                             1476
WEATHER
DISTANCE                        NaN
Name: 2245, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             181
KM                             1487
WEATHER
DISTANCE                        NaN
Name: 2246, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             182
KM                              917
WEATHER
DISTANCE                        NaN
Name: 2247, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             183
KM                             1083
WEATHER
DISTANCE                        NaN
Name: 2248, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             184
KM                              365
WEATHER
DISTANCE                        NaN
Name: 2249, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             184
KM                              389
WEATHER
DISTANCE                        NaN
Name: 2250, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             184
KM                              418
WEATHER
DISTANCE                        NaN
Name: 2251, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             185
KM                             1582
WEATHER
DISTANCE                        NaN
Name: 2252, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             185
KM                             1611
WEATHER
DISTANCE                        NaN
Name: 2253, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             185
KM                             1635
WEATHER
DISTANCE                        NaN
Name: 2254, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             186
KM                              747
WEATHER
DISTANCE                        NaN
Name: 2255, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             187
KM                             1253
WEATHER
DISTANCE                        NaN
Name: 2256, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             188
KM                              481
WEATHER
DISTANCE                        NaN
Name: 2257, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             188
KM                              494
WEATHER
DISTANCE                        NaN
Name: 2258, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             188
KM                              511
WEATHER
DISTANCE                        NaN
Name: 2259, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             188
KM                              528
WEATHER
DISTANCE                        NaN
Name: 2260, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             188
KM                              551
WEATHER
DISTANCE                        NaN
Name: 2261, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             188
KM                              559
WEATHER
DISTANCE                        NaN
Name: 2262, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             189
KM                             1441
WEATHER
DISTANCE                        NaN
Name: 2263, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             189
KM                             1449
WEATHER
DISTANCE                        NaN
Name: 2264, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             189
KM                             1472
WEATHER
DISTANCE                        NaN
Name: 2265, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             189
KM                             1489
WEATHER
DISTANCE                        NaN
Name: 2266, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             189
KM                             1506
WEATHER
DISTANCE                        NaN
Name: 2267, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             189
KM                             1519
WEATHER
DISTANCE                        NaN
Name: 2268, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              19
KM                             1890
WEATHER
DISTANCE                        NaN
Name: 2269, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              19
KM                             1895
WEATHER
DISTANCE                        NaN
Name: 2270, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              19
KM                             1899
WEATHER
DISTANCE                        NaN
Name: 2271, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             190
KM                              382
WEATHER
DISTANCE                        NaN
Name: 2272, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             191
KM                             1618
WEATHER
DISTANCE                        NaN
Name: 2273, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             192
KM                              626
WEATHER
DISTANCE                        NaN
Name: 2274, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             193
KM                             1374
WEATHER
DISTANCE                        NaN
Name: 2275, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             194
KM                              106
WEATHER
DISTANCE                        NaN
Name: 2276, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             195
KM                             1894
WEATHER
DISTANCE                        NaN
Name: 2277, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             196
KM                              129
WEATHER
DISTANCE                        NaN
Name: 2278, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             197
KM                             1871
WEATHER
DISTANCE                        NaN
Name: 2279, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             198
KM                              527
WEATHER
DISTANCE                        NaN
Name: 2280, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             198
KM                              546
WEATHER
DISTANCE                        NaN
Name: 2281, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             198
KM                              553
WEATHER
DISTANCE                        NaN
Name: 2282, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             198
KM                              576
WEATHER
DISTANCE                        NaN
Name: 2283, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             199
KM                             1424
WEATHER
DISTANCE                        NaN
Name: 2284, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             199
KM                             1447
WEATHER
DISTANCE                        NaN
Name: 2285, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             199
KM                             1454
WEATHER
DISTANCE                        NaN
Name: 2286, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             199
KM                             1473
WEATHER
DISTANCE                        NaN
Name: 2287, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               2
KM                              971
WEATHER
DISTANCE                        NaN
Name: 2288, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                               2
KM                              974
WEATHER
DISTANCE                        NaN
Name: 2289, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              20
KM                              375
WEATHER
DISTANCE                        NaN
Name: 2290, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             200
KM                              442
WEATHER
DISTANCE                        NaN
Name: 2291, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             201
KM                             1558
WEATHER
DISTANCE                        NaN
Name: 2292, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             202
KM                              592
WEATHER
DISTANCE                        NaN
Name: 2293, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             202
KM                              601
WEATHER
DISTANCE                        NaN
Name: 2294, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             202
KM                              621
WEATHER
DISTANCE                        NaN
Name: 2295, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             202
KM                              627
WEATHER
DISTANCE                        NaN
Name: 2296, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             202
KM                              640
WEATHER
DISTANCE                        NaN
Name: 2297, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             203
KM                             1360
WEATHER
DISTANCE                        NaN
Name: 2298, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             203
KM                             1373
WEATHER
DISTANCE                        NaN
Name: 2299, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             203
KM                             1379
WEATHER
DISTANCE                        NaN
Name: 2300, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             203
KM                             1399
WEATHER
DISTANCE                        NaN
Name: 2301, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             203
KM                             1408
WEATHER
DISTANCE                        NaN
Name: 2302, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              114
WEATHER
DISTANCE                        NaN
Name: 2303, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              137
WEATHER
DISTANCE                        NaN
Name: 2304, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              211
WEATHER
DISTANCE                        NaN
Name: 2305, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              228
WEATHER
DISTANCE                        NaN
Name: 2306, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              246
WEATHER
DISTANCE                        NaN
Name: 2307, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              267
WEATHER
DISTANCE                        NaN
Name: 2308, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              307
WEATHER
DISTANCE                        NaN
Name: 2309, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              348
WEATHER
DISTANCE                        NaN
Name: 2310, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              404
WEATHER
DISTANCE                        NaN
Name: 2311, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              439
WEATHER
DISTANCE                        NaN
Name: 2312, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              485
WEATHER
DISTANCE                        NaN
Name: 2313, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              524
WEATHER
DISTANCE                        NaN
Name: 2314, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              550
WEATHER
DISTANCE                        NaN
Name: 2315, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              577
WEATHER
DISTANCE                        NaN
Name: 2316, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              593
WEATHER
DISTANCE                        NaN
Name: 2317, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              644
WEATHER
DISTANCE                        NaN
Name: 2318, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              709
WEATHER
DISTANCE                        NaN
Name: 2319, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              735
WEATHER
DISTANCE                        NaN
Name: 2320, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             204
KM                              751
WEATHER
DISTANCE                        NaN
Name: 2321, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1249
WEATHER
DISTANCE                        NaN
Name: 2322, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1265
WEATHER
DISTANCE                        NaN
Name: 2323, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1291
WEATHER
DISTANCE                        NaN
Name: 2324, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1356
WEATHER
DISTANCE                        NaN
Name: 2325, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1407
WEATHER
DISTANCE                        NaN
Name: 2326, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1423
WEATHER
DISTANCE                        NaN
Name: 2327, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1450
WEATHER
DISTANCE                        NaN
Name: 2328, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1476
WEATHER
DISTANCE                        NaN
Name: 2329, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1515
WEATHER
DISTANCE                        NaN
Name: 2330, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1561
WEATHER
DISTANCE                        NaN
Name: 2331, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1596
WEATHER
DISTANCE                        NaN
Name: 2332, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1652
WEATHER
DISTANCE                        NaN
Name: 2333, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1693
WEATHER
DISTANCE                        NaN
Name: 2334, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1733
WEATHER
DISTANCE                        NaN
Name: 2335, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1754
WEATHER
DISTANCE                        NaN
Name: 2336, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1772
WEATHER
DISTANCE                        NaN
Name: 2337, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1789
WEATHER
DISTANCE                        NaN
Name: 2338, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1863
WEATHER
DISTANCE                        NaN
Name: 2339, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             205
KM                             1886
WEATHER
DISTANCE                        NaN
Name: 2340, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             206
KM                              174
WEATHER
DISTANCE                        NaN
Name: 2341, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             207
KM                             1826
WEATHER
DISTANCE                        NaN
Name: 2342, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             208
KM                              777
WEATHER
DISTANCE                        NaN
Name: 2343, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             209
KM                              164
WEATHER
DISTANCE                        NaN
Name: 2344, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              21
KM                              616
WEATHER
DISTANCE                        NaN
Name: 2345, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             210
KM                             1836
WEATHER
DISTANCE                        NaN
Name: 2346, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             211
KM                              446
WEATHER
DISTANCE                        NaN
Name: 2347, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             211
KM                              493
WEATHER
DISTANCE                        NaN
Name: 2348, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             212
KM                             1507
WEATHER
DISTANCE                        NaN
Name: 2349, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             212
KM                             1554
WEATHER
DISTANCE                        NaN
Name: 2350, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             213
KM                              511
WEATHER
DISTANCE                        NaN
Name: 2351, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             213
KM                              547
WEATHER
DISTANCE                        NaN
Name: 2352, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             213
KM                              559
WEATHER
DISTANCE                        NaN
Name: 2353, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             213
KM                              594
WEATHER
DISTANCE                        NaN
Name: 2354, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             214
KM                             1406
WEATHER
DISTANCE                        NaN
Name: 2355, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             214
KM                             1441
WEATHER
DISTANCE                        NaN
Name: 2356, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             214
KM                             1453
WEATHER
DISTANCE                        NaN
Name: 2357, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             214
KM                             1489
WEATHER
DISTANCE                        NaN
Name: 2358, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             215
KM                              468
WEATHER
DISTANCE                        NaN
Name: 2359, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             216
KM                             1532
WEATHER
DISTANCE                        NaN
Name: 2360, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             217
KM                             1011
WEATHER
DISTANCE                        NaN
Name: 2361, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             217
KM                              959
WEATHER
DISTANCE                        NaN
Name: 2362, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             218
KM                             1041
WEATHER
DISTANCE                        NaN
Name: 2363, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             218
KM                              989
WEATHER
DISTANCE                        NaN
Name: 2364, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             219
KM                               44
WEATHER
DISTANCE                        NaN
Name: 2365, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             219
KM                               73
WEATHER
DISTANCE                        NaN
Name: 2366, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              22
KM                             1384
WEATHER
DISTANCE                        NaN
Name: 2367, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             220
KM                             1927
WEATHER
DISTANCE                        NaN
Name: 2368, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             220
KM                             1956
WEATHER
DISTANCE                        NaN
Name: 2369, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             221
KM                             1006
WEATHER
DISTANCE                        NaN
Name: 2370, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             221
KM                             1016
WEATHER
DISTANCE                        NaN
Name: 2371, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             221
KM                             1042
WEATHER
DISTANCE                        NaN
Name: 2372, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             221
KM                              996
WEATHER
DISTANCE                        NaN
Name: 2373, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             222
KM                             1004
WEATHER
DISTANCE                        NaN
Name: 2374, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             222
KM                              958
WEATHER
DISTANCE                        NaN
Name: 2375, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             222
KM                              984
WEATHER
DISTANCE                        NaN
Name: 2376, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             222
KM                              994
WEATHER
DISTANCE                        NaN
Name: 2377, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             223
KM                             1251
WEATHER
DISTANCE                        NaN
Name: 2378, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             224
KM                              160
WEATHER
DISTANCE                        NaN
Name: 2379, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             225
KM                             1840
WEATHER
DISTANCE                        NaN
Name: 2380, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             226
KM                              802
WEATHER
DISTANCE                        NaN
Name: 2381, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             226
KM                              808
WEATHER
DISTANCE                        NaN
Name: 2382, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             226
KM                              818
WEATHER
DISTANCE                        NaN
Name: 2383, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             226
KM                              838
WEATHER
DISTANCE                        NaN
Name: 2384, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             226
KM                              850
WEATHER
DISTANCE                        NaN
Name: 2385, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             227
KM                             1150
WEATHER
DISTANCE                        NaN
Name: 2386, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             227
KM                             1162
WEATHER
DISTANCE                        NaN
Name: 2387, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             227
KM                             1182
WEATHER
DISTANCE                        NaN
Name: 2388, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             227
KM                             1192
WEATHER
DISTANCE                        NaN
Name: 2389, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             227
KM                             1198
WEATHER
DISTANCE                        NaN
Name: 2390, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             228
KM                              587
WEATHER
DISTANCE                        NaN
Name: 2391, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             229
KM                             1413
WEATHER
DISTANCE                        NaN
Name: 2392, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              23
KM                               66
WEATHER
DISTANCE                        NaN
Name: 2393, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             230
KM                              830
WEATHER
DISTANCE                        NaN
Name: 2394, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             231
KM                             1170
WEATHER
DISTANCE                        NaN
Name: 2395, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             232
KM                              896
WEATHER
DISTANCE                        NaN
Name: 2396, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             233
KM                             1104
WEATHER
DISTANCE                        NaN
Name: 2397, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             234
KM                              597
WEATHER
DISTANCE                        NaN
Name: 2398, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             234
KM                              615
WEATHER
DISTANCE                        NaN
Name: 2399, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             234
KM                              638
WEATHER
DISTANCE                        NaN
Name: 2400, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             234
KM                              663
WEATHER
DISTANCE                        NaN
Name: 2401, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             234
KM                              696
WEATHER
DISTANCE                        NaN
Name: 2402, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             234
KM                              714
WEATHER
DISTANCE                        NaN
Name: 2403, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             235
KM                             1286
WEATHER
DISTANCE                        NaN
Name: 2404, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             235
KM                             1304
WEATHER
DISTANCE                        NaN
Name: 2405, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             235
KM                             1337
WEATHER
DISTANCE                        NaN
Name: 2406, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             235
KM                             1362
WEATHER
DISTANCE                        NaN
Name: 2407, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             235
KM                             1385
WEATHER
DISTANCE                        NaN
Name: 2408, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             235
KM                             1403
WEATHER
DISTANCE                        NaN
Name: 2409, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             236
KM                              332
WEATHER
DISTANCE                        NaN
Name: 2410, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             236
KM                              360
WEATHER
DISTANCE                        NaN
Name: 2411, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             236
KM                              370
WEATHER
DISTANCE                        NaN
Name: 2412, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             237
KM                             1630
WEATHER
DISTANCE                        NaN
Name: 2413, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             237
KM                             1640
WEATHER
DISTANCE                        NaN
Name: 2414, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             237
KM                             1668
WEATHER
DISTANCE                        NaN
Name: 2415, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             238
KM                              356
WEATHER
DISTANCE                        NaN
Name: 2416, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             238
KM                              384
WEATHER
DISTANCE                        NaN
Name: 2417, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             239
KM                             1616
WEATHER
DISTANCE                        NaN
Name: 2418, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             239
KM                             1644
WEATHER
DISTANCE                        NaN
Name: 2419, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              24
KM                             1934
WEATHER
DISTANCE                        NaN
Name: 2420, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             240
KM                              712
WEATHER
DISTANCE                        NaN
Name: 2421, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             240
KM                              714
WEATHER
DISTANCE                        NaN
Name: 2422, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             240
KM                              749
WEATHER
DISTANCE                        NaN
Name: 2423, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             241
KM                             1251
WEATHER
DISTANCE                        NaN
Name: 2424, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             241
KM                             1286
WEATHER
DISTANCE                        NaN
Name: 2425, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             241
KM                             1288
WEATHER
DISTANCE                        NaN
Name: 2426, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             242
KM                              846
WEATHER
DISTANCE                        NaN
Name: 2427, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             243
KM                             1154
WEATHER
DISTANCE                        NaN
Name: 2428, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             244
KM                              622
WEATHER
DISTANCE                        NaN
Name: 2429, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             244
KM                              624
WEATHER
DISTANCE                        NaN
Name: 2430, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             244
KM                              638
WEATHER
DISTANCE                        NaN
Name: 2431, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             245
KM                             1362
WEATHER
DISTANCE                        NaN
Name: 2432, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             245
KM                             1376
WEATHER
DISTANCE                        NaN
Name: 2433, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             245
KM                             1378
WEATHER
DISTANCE                        NaN
Name: 2434, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             246
KM                              508
WEATHER
DISTANCE                        NaN
Name: 2435, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             246
KM                              516
WEATHER
DISTANCE                        NaN
Name: 2436, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             246
KM                              530
WEATHER
DISTANCE                        NaN
Name: 2437, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             246
KM                              544
WEATHER
DISTANCE                        NaN
Name: 2438, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             246
KM                              550
WEATHER
DISTANCE                        NaN
Name: 2439, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             246
KM                              557
WEATHER
DISTANCE                        NaN
Name: 2440, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             247
KM                             1443
WEATHER
DISTANCE                        NaN
Name: 2441, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             247
KM                             1450
WEATHER
DISTANCE                        NaN
Name: 2442, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             247
KM                             1456
WEATHER
DISTANCE                        NaN
Name: 2443, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             247
KM                             1470
WEATHER
DISTANCE                        NaN
Name: 2444, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             247
KM                             1484
WEATHER
DISTANCE                        NaN
Name: 2445, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             247
KM                             1492
WEATHER
DISTANCE                        NaN
Name: 2446, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             248
KM                              599
WEATHER
DISTANCE                        NaN
Name: 2447, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             249
KM                             1401
WEATHER
DISTANCE                        NaN
Name: 2448, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              25
KM                              931
WEATHER
DISTANCE                        NaN
Name: 2449, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             250
KM                              821
WEATHER
DISTANCE                        NaN
Name: 2450, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             250
KM                              849
WEATHER
DISTANCE                        NaN
Name: 2451, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             251
KM                             1151
WEATHER
DISTANCE                        NaN
Name: 2452, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             251
KM                             1179
WEATHER
DISTANCE                        NaN
Name: 2453, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             252
KM                              491
WEATHER
DISTANCE                        NaN
Name: 2454, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             253
KM                             1509
WEATHER
DISTANCE                        NaN
Name: 2455, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             254
KM                              103
WEATHER
DISTANCE                        NaN
Name: 2456, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             254
KM                              110
WEATHER
DISTANCE                        NaN
Name: 2457, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             254
KM                               72
WEATHER
DISTANCE                        NaN
Name: 2458, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             255
KM                             1890
WEATHER
DISTANCE                        NaN
Name: 2459, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             255
KM                             1897
WEATHER
DISTANCE                        NaN
Name: 2460, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             255
KM                             1928
WEATHER
DISTANCE                        NaN
Name: 2461, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             256
KM                              861
WEATHER
DISTANCE                        NaN
Name: 2462, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             257
KM                             1139
WEATHER
DISTANCE                        NaN
Name: 2463, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             258
KM                              107
WEATHER
DISTANCE                        NaN
Name: 2464, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             258
KM                              142
WEATHER
DISTANCE                        NaN
Name: 2465, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             259
KM                             1858
WEATHER
DISTANCE                        NaN
Name: 2466, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             259
KM                             1893
WEATHER
DISTANCE                        NaN
Name: 2467, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              26
KM                             1069
WEATHER
DISTANCE                        NaN
Name: 2468, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             260
KM                              972
WEATHER
DISTANCE                        NaN
Name: 2469, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             261
KM                             1028
WEATHER
DISTANCE                        NaN
Name: 2470, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             262
KM                              381
WEATHER
DISTANCE                        NaN
Name: 2471, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             262
KM                              406
WEATHER
DISTANCE                        NaN
Name: 2472, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             262
KM                              417
WEATHER
DISTANCE                        NaN
Name: 2473, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             262
KM                              477
WEATHER
DISTANCE                        NaN
Name: 2474, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             263
KM                             1583
WEATHER
DISTANCE                        NaN
Name: 2475, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             263
KM                             1594
WEATHER
DISTANCE                        NaN
Name: 2476, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             263
KM                             1619
WEATHER
DISTANCE                        NaN
Name: 2477, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             264
KM                              287
WEATHER
DISTANCE                        NaN
Name: 2478, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             264
KM                              313
WEATHER
DISTANCE                        NaN
Name: 2479, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             265
KM                             1687
WEATHER
DISTANCE                        NaN
Name: 2480, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             265
KM                             1713
WEATHER
DISTANCE                        NaN
Name: 2481, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             266
KM                              498
WEATHER
DISTANCE                        NaN
Name: 2482, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             266
KM                              566
WEATHER
DISTANCE                        NaN
Name: 2483, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             267
KM                             1434
WEATHER
DISTANCE                        NaN
Name: 2484, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             267
KM                             1502
WEATHER
DISTANCE                        NaN
Name: 2485, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             268
KM                              719
WEATHER
DISTANCE                        NaN
Name: 2486, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             269
KM                             1281
WEATHER
DISTANCE                        NaN
Name: 2487, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              27
KM                              527
WEATHER
DISTANCE                        NaN
Name: 2488, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              27
KM                              545
WEATHER
DISTANCE                        NaN
Name: 2489, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             270
KM                              688
WEATHER
DISTANCE                        NaN
Name: 2490, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             271
KM                             1312
WEATHER
DISTANCE                        NaN
Name: 2491, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             272
KM                               65
WEATHER
DISTANCE                        NaN
Name: 2492, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             272
KM                               78
WEATHER
DISTANCE                        NaN
Name: 2493, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             273
KM                             1922
WEATHER
DISTANCE                        NaN
Name: 2494, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             273
KM                             1935
WEATHER
DISTANCE                        NaN
Name: 2495, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             274
KM                              780
WEATHER
DISTANCE                        NaN
Name: 2496, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             274
KM                              834
WEATHER
DISTANCE                        NaN
Name: 2497, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             275
KM                             1166
WEATHER
DISTANCE                        NaN
Name: 2498, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             275
KM                             1220
WEATHER
DISTANCE                        NaN
Name: 2499, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             276
KM                              754
WEATHER
DISTANCE                        NaN
Name: 2500, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             277
KM                             1246
WEATHER
DISTANCE                        NaN
Name: 2501, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             278
KM                              686
WEATHER
DISTANCE                        NaN
Name: 2502, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             279
KM                             1314
WEATHER
DISTANCE                        NaN
Name: 2503, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              28
KM                             1455
WEATHER
DISTANCE                        NaN
Name: 2504, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              28
KM                             1473
WEATHER
DISTANCE                        NaN
Name: 2505, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             280
KM                              617
WEATHER
DISTANCE                        NaN
Name: 2506, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             281
KM                             1383
WEATHER
DISTANCE                        NaN
Name: 2507, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             282
KM                              374
WEATHER
DISTANCE                        NaN
Name: 2508, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             282
KM                              443
WEATHER
DISTANCE                        NaN
Name: 2509, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             283
KM                             1557
WEATHER
DISTANCE                        NaN
Name: 2510, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             283
KM                             1626
WEATHER
DISTANCE                        NaN
Name: 2511, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             284
KM                              744
WEATHER
DISTANCE                        NaN
Name: 2512, dtype: object

NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             285
KM                             1256
WEATHER
DISTANCE                        NaN
Name: 2513, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             286
KM                              854
WEATHER
DISTANCE                        NaN
Name: 2514, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             287
KM                             1146
WEATHER
DISTANCE                        NaN
Name: 2515, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             288
KM                              524
WEATHER
DISTANCE                        NaN
Name: 2516, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             289
KM                             1476
WEATHER
DISTANCE                        NaN
Name: 2517, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                              29
KM                              275
WEATHER
DISTANCE                        NaN
Name: 2518, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             290
KM                              299
WEATHER
DISTANCE                        NaN
Name: 2519, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             291
KM                             1701
WEATHER
DISTANCE                        NaN
Name: 2520, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              743
WEATHER
DISTANCE                        NaN
Name: 2521, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              761
WEATHER
DISTANCE                        NaN
Name: 2522, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              767
WEATHER
DISTANCE                        NaN
Name: 2523, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              768
WEATHER
DISTANCE                        NaN
Name: 2524, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              775
WEATHER
DISTANCE                        NaN
Name: 2525, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              776
WEATHER
DISTANCE                        NaN
Name: 2526, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              782
WEATHER
DISTANCE                        NaN
Name: 2527, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              789
WEATHER
DISTANCE                        NaN
Name: 2528, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             292
KM                              792
WEATHER
DISTANCE                        NaN
Name: 2529, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1208
WEATHER
DISTANCE                        NaN
Name: 2530, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1211
WEATHER
DISTANCE                        NaN
Name: 2531, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1218
WEATHER
DISTANCE                        NaN
Name: 2532, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1224
WEATHER
DISTANCE                        NaN
Name: 2533, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1225
WEATHER
DISTANCE                        NaN
Name: 2534, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1232
WEATHER
DISTANCE                        NaN
Name: 2535, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1233
WEATHER
DISTANCE                        NaN
Name: 2536, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1239
WEATHER
DISTANCE                        NaN
Name: 2537, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             293
KM                             1257
WEATHER
DISTANCE                        NaN
Name: 2538, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             294
KM                              400
WEATHER
DISTANCE                        NaN
Name: 2539, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             294
KM                              422
WEATHER
DISTANCE                        NaN
Name: 2540, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             294
KM                              459
WEATHER
DISTANCE                        NaN
Name: 2541, dtype: object
NON PRESENTE
DATETIME_UTC    2018-09-01 01:00:00
KEY                             295
KM                             1541
WEATHER
DISTANCE                        NaN
Name: 2542, dtype: object

KeyboardInterrupt: